### ISSUE TITLE
Video "locked as private" after upload

### ISSUE THREAD

**Issue by PiPauwels** [tokland/youtube-upload#306]
I've succesfully uploaded a video, but upon completion I received an e-mail from Google stating:

> We’re reaching out as it’s important you know that your video has been **locked as private**. This is because it was uploaded to YouTube using a third-party service that hasn’t yet been through our verification process.

Sharing the video with someone else was impossible because of this. It seems that all videos uploaded with youtube-upload get "locked as private" on my account.

More info: [Youtube Help: Videos locked as private](https://support.google.com/youtube/answer/7300965?visit_id=637352843310196577-3439988230&p=locked_asprivate&hl=en&rd=1)

**Comment by BenGirone** [comment]
Yep. They also have made it so you can no longer use puppeteer to access youtube. I think the only way now is to buy Gsuite and make your internal credentials

Edit: Gsuite is no longer an option either.

**Comment by schneemaier** [comment]
You have to go through the application verification process.

From the email sent earlier tis year:
"
Hi YouTube Developer,
 
We're writing to let you know about upcoming changes to the YouTube API Services that will affect API projects created after July 28, 2020.
 
All videos uploaded via the videos.insert endpoint from unverified API Projects created after this date will be restricted to private viewing mode. To lift this restriction, each project must undergo an audit to verify compliance with the Terms of Service.
 
Creators who use an affected project to upload video will receive an email explaining that their video is locked as private, and that they can avoid the restriction by using an official or audited service.
 
Existing API projects will not be affected by this change, but we strongly recommend that all developers complete a compliance audit for their projects to ensure continued access to the YouTube API Services.
 
Thanks,YouTube API Services Team
"

Audit link: [https://support.google.com/youtube/contact/yt_api_form](https://support.google.com/youtube/contact/yt_api_form)

It is a bit tricky to explain them how youtube-upload works, but it is possible..

**Comment by zilton7** [comment]
I was trying to get verifieid it took sometime to do so and I am still not able to upload without gettin videos locked, youtube supports last email isn't stating anything if i was or wasnt't verified

`
Hi,

Thanks for working with us on the YouTube API Services compliance review.

We have completed your review and do not require any further actions from you at this time. We may reach out again to re-review your API Client for compliance with YouTube API Services Terms and Policies.

We appreciate your time working with us on this and please continue to comply with the YouTube API Services Terms and Policies.

Please do not reply to this email as this email thread will no longer be monitored, you may submit this form to get in touch with us for any queries/concerns.
`

**Comment by schneemaier** [comment]
> We have completed your review and do not require any further actions from you at this time.

This means that you are reviewed and found in compliance with YouTube API, so you uploads should work now without being locked into private

**Comment by zilton7** [comment]
Yeah that's what i have assumed too but it still gets locked...

- Zil

**Comment by schneemaier** [comment]
> Yeah that's what i have assumed too but it still gets locked... - Zil

Sometimes it takes time to roll out these changes. Does it work now?

**Comment by zilton7** [comment]
> > Yeah that's what i have assumed too but it still gets locked... - Zil
> 
> Sometimes it takes time to roll out these changes. Does it work now?

yes, finally now it seem to work as expected. It took long time, probably because it was a weekend?

**Comment by PiPauwels** [comment]
Sorry to break the bad news, but I just uploaded a video and it still got flagged "locked as private".

**Comment by shenhavmor10** [comment]
> I was trying to get verifieid it took sometime to do so and I am still not able to upload without gettin videos locked, youtube supports last email isn't stating anything if i was or wasnt't verified
> 
> `
> Hi,
> 
> Thanks for working with us on the YouTube API Services compliance review.
> 
> We have completed your review and do not require any further actions from you at this time. We may reach out again to re-review your API Client for compliance with YouTube API Services Terms and Policies.
> 
> We appreciate your time working with us on this and please continue to comply with the YouTube API Services Terms and Policies.
> 
> Please do not reply to this email as this email thread will no longer be monitored, you may submit this form to get in touch with us for any queries/concerns.
> `

hey man can i get some help ? what do you mean by getting verified may i get a link or anything?

**Comment by andho** [comment]
@zilton7 did you verify it from the "OAuth consent screen" > "EDIT APP" in the Google developer console? Then fill in the fields:
- Application logo
- Authorized domains
- Application Homepage link
- Application Privacy Policy link
- Application Terms of Service link

And after that, click on "Submit for verification" button?

**Comment by shenhavmor10** [comment]
I did but now youtube requests for a video :(
demo .
tbh today it worked for me but i dont know if i am verified because i do
need to send them a demo

‫בתאריך יום ב׳, 12 באוק׳ 2020 ב-18:44 מאת ‪Amjad Mohamed‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Lambik** [comment]
Does anyone have an example privacy policy and ToS text that gets accepted by them? And apparently I also need to include a demo video on youtube of "how the app is used"...

**Comment by lovemyliwu** [comment]
so sad, but let me try verify.

**Comment by feacluster** [comment]
YouTube makes this process incedibly complicated and confusing . They think we're all large corporations with huge IT staff and $$ to understand what they want us to do. The truth is most of YouTube is run by mom and pop folks who have zero IT knowledge.

**Comment by lovemyliwu** [comment]
good news, I was passed `YouTube API Services compliance review`, the new upload video can be public. :tada: 

cost time: 8 days

**Comment by feacluster** [comment]
> good news, I was passed `YouTube API Services compliance review`, the new upload video can be public. 
> 
> cost time: 8 days

Can you share what they requested? I believe you have to show your app running on a site with it's own domain name and with a SSL certificate, so https accessible, not http.

**Comment by lovemyliwu** [comment]
@feacluster sure, but not difficult, simply, I give them a screen record video to show how I used this tool to upload video in command shell, and show the problem I faced(after upload, in the video edit page can't change to public).

**Comment by PiPauwels** [comment]
Just tried out another upload. Next to still being "locked as private", the video stays in a state "uploading" when you check it on studio.youtube.com, even after the uploader script has finished.

**Comment by feacluster** [comment]
> @feacluster sure, but not difficult, simply, I give them a screen record video to show how I used this tool to upload video in command shell, and show the problem I faced(after upload, in the video edit page can't change to public).

Did you recall if you requested "Restriced scopes" when you submitted your app for verification? I don't really understand whether I need them or not.

**Comment by feacluster** [comment]
My app passed the verification from YouTube. But still when I upload videos via the youtube-upload script they are still being marked as Private. They asked for a demo video that shows how the error happens. I sent them that but seems they did not like it and want to see more details from how the youtube-upload script works alongwith how it is attached to the project.  Here is their email:

Unfortunately, we found your YouTube demo video to be insufficient for verification, because it does not showcase the client id and no permission page  your application is currently accessing. (Please see the attached screenshot for reference of client id)

Please make sure that your screencast hosted on youtube includes all of the following requirements:

    Please make sure that your screencast is hosted on Youtube
    Please make sure that your screencast exposes your entire screen, so that we may see the url in the search bar.
    Show how your app uses the requested scopes.

Note: Please provide an Updated YouTube link by showing the project number, so that we can proceed with the approval process.

Thank you for your patience. Please do not hesitate to reach out to us if you have questions or concerns.

**Comment by lavAzza2** [comment]
@Feacluster @lovemyliwu
Help me please.
What is type of application you choose?
Do you buy G Suit account for that?
At OAuth consent screen written "Depending on how you configure your OAuth screen, you may have to submit your app for verification ." In what case is verification not needed?

I have ssl website for my app, but I plan use it own.

**Comment by feacluster** [comment]
> 
> 
> @feacluster @lovemyliwu
> Help me please.
> What is type of application you choose?
> Do you buy G Suit account for that?
> At OAuth consent screen written "Depending on how you configure your OAuth screen, you may have to submit your app for verification ." In what case is verification not needed?
> 
> I have ssl website for my app, but I plan use it own.

I think Application was Other or TV/limited input device.  You don't need G suite.

If the app is uploading to your YouTube account like this youtube-upload is, then it needs verification. At least that is my understanding.

**Comment by lavAzza2** [comment]
Thank you, @feacluster.
Ok, I think I found easy way. I create project and select "Desktop app", I not upload app icon and not write website url. And in this case verification status is "Verification not required". But token grant rate is still 10000. As I know it is 6 video per day.
This way for those who make an application for personal use.

**Comment by feacluster** [comment]
> 
> 
> Thank you, @feacluster.
> Ok, I think I found easy way. I create project and select "Desktop app", I not upload app icon and not write website url. And in this case verification status is "Verification not required". But token grant rate is still 10000. As I know it is 6 video per day.
> This way for those who make an application for personal use.

Good to know that worked for you. I had not tried that. There is also another way to upload youtube videos usnig a browser based method.. See: https://github.com/linouk23/youtube_uploader_selenium  I have not tried it but will keep it as backup in case YouTube pulls the plug on whatever I am doing !

**Comment by lavAzza2** [comment]
> There is also another way to upload youtube videos usnig a browser based method.. See: https://github.com/linouk23/youtube_uploader_selenium

Yes I tryed this script but it not work for me because It use Linux GUI and I am not.

**Comment by lovemyliwu** [comment]
@lavAzza2 

It's not the `Google Cloud Platform Console` bussiness, it only related to `YouTube API`, so no matter how you configure your project in GCP, uploaded video always private.

You should fill this form https://support.google.com/youtube/contact/yt_api_form

**Comment by harbinger0x7c0** [comment]
I ran into this issue when I did not supply a --privacy flag. Supplying --privacy=private on another attempt did not cause the video to be locked when the upload was complete.

**Comment by AlexScotland** [comment]
> I ran into this issue when I did not supply a --privacy flag. Supplying --privacy=private on another attempt did not cause the video to be locked when the upload was complete.

Issue only occurs on Public videos.

**Comment by ScottishWildlifeGarden** [comment]
> > > Yeah that's what i have assumed too but it still gets locked... - Zil
> > 
> > 
> > Sometimes it takes time to roll out these changes. Does it work now?
> 
> yes, finally now it seem to work as expected. It took long time, probably because it was a weekend?

I have the same issue with live streams created with the API get marked as Private even after getting my App Verified in OAuth and after filling in the Audit form https://support.google.com/youtube/contact/yt_api_form.

How long did it take for yours to start working? It's been a week or so for me so far. Thanks

**Comment by samuelya** [comment]
@ScottishWildlifeGarden i am in similar possition 

> > > > Yeah that's what i have assumed too but it still gets locked... - Zil
> > > 
> > > 
> > > Sometimes it takes time to roll out these changes. Does it work now?
> > 
> > 
> > yes, finally now it seem to work as expected. It took long time, probably because it was a weekend?
> 
> I have the same issue with live streams created with the API get marked as Private even after getting my App Verified in OAuth and after filling in the Audit form https://support.google.com/youtube/contact/yt_api_form.
> 
> How long did it take for yours to start working? It's been a week or so for me so far. Thanks

I am in a similar situation would able to let me know how long it will take and what the next step is after you submit google review form? Thanks

**Comment by ScottishWildlifeGarden** [comment]
> @ScottishWildlifeGarden i am in similar possition
> 
> > > > > Yeah that's what i have assumed too but it still gets locked... - Zil
> > > > 
> > > > 
> > > > Sometimes it takes time to roll out these changes. Does it work now?
> > > 
> > > 
> > > yes, finally now it seem to work as expected. It took long time, probably because it was a weekend?
> > 
> > 
> > I have the same issue with live streams created with the API get marked as Private even after getting my App Verified in OAuth and after filling in the Audit form https://support.google.com/youtube/contact/yt_api_form.
> > How long did it take for yours to start working? It's been a week or so for me so far. Thanks
> 
> I am in a similar situation would able to let me know how long it will take and what the next step is after you submit google review form? Thanks

Started working for me after another week so I think it was about 2 weeks in total. So hang tight.

**Comment by Alyetama** [comment]
I'm having this issue even after 2 weeks of verifying my app...

**Comment by aryan29** [comment]
> I was trying to get verifieid it took sometime to do so and I am still not able to upload without gettin videos locked, youtube supports last email isn't stating anything if i was or wasnt't verified
> 
> `
> Hi,
> 
> Thanks for working with us on the YouTube API Services compliance review.
> 
> We have completed your review and do not require any further actions from you at this time. We may reach out again to re-review your API Client for compliance with YouTube API Services Terms and Policies.
> 
> We appreciate your time working with us on this and please continue to comply with the YouTube API Services Terms and Policies.
> 
> Please do not reply to this email as this email thread will no longer be monitored, you may submit this form to get in touch with us for any queries/concerns.
> `

Hey I received the same email and when I am trying to upload videos they are still marking it as **Private(Locked)** and I am getting a mail that my video violates there **spams,deceptive policies and scams policy**      

I saw that the issues got solved for you after some time , approximately how much time it takes and does it works good now too or youtube teams keeps creating some problem

**Comment by Linux2010** [comment]
> > I was trying to get verifieid it took sometime to do so and I am still not able to upload without gettin videos locked, youtube supports last email isn't stating anything if i was or wasnt't verified
> > `
> > Hi,
> > Thanks for working with us on the YouTube API Services compliance review.
> > We have completed your review and do not require any further actions from you at this time. We may reach out again to re-review your API Client for compliance with YouTube API Services Terms and Policies.
> > We appreciate your time working with us on this and please continue to comply with the YouTube API Services Terms and Policies.
> > Please do not reply to this email as this email thread will no longer be monitored, you may submit this form to get in touch with us for any queries/concerns.
> > `
> 
> Hey I received the same email and when I am trying to upload videos they are still marking it as **Private(Locked)** and I am getting a mail that my video violates there **spams,deceptive policies and scams policy**
> 
> I saw that the issues got solved for you after some time , approximately how much time it takes and does it works good now too or youtube teams keeps creating some problem

Hey I received the same email . Have you solved this problem and how?

**Comment by pcislocked** [comment]
Just wanted to write my experience with the youtube api team

I sent a quota request directly linking this repository and stating my use case(just personal use - specifically reuploading lecture recordings from sharepoint to youtube as unlisted) - got my quota increase within a week. I asked for and got 20k per day - which is more than enough for me. Quota got increased and the keys started working immediately after the response mail.

**Comment by adriel** [comment]
For those unaware, here is where Google talks about new requirements, which came into effect late 2020.

https://developers.google.com/youtube/v3/revision_history#release_notes_07_28_2020

https://developers.google.com/youtube/v3/docs/videos
![image](https://user-images.githubusercontent.com/154217/145957206-1074748d-a6d8-4581-a0a8-8b099fa4ef4c.png)

![image](https://user-images.githubusercontent.com/154217/145957714-9eb74c14-31e0-4706-8890-1c340df8c14c.png)

**Comment by daviareias** [comment]
Thanks I wasted 4 hours trying to set this up, just to find out about this.

**Comment by beckyandcloud** [comment]
> Just wanted to write my experience with the youtube api team
> 
> I sent a quota request directly linking this repository and stating my use case(just personal use - specifically reuploading lecture recordings from sharepoint to youtube as unlisted) - got my quota increase within a week. I asked for and got 20k per day - which is more than enough for me. Quota got increased and the keys started working immediately after the response mail.

Did you fill the whole super long form for this or did you use another way?
I'm new to this and the official forms seems super long and complicated :/
Thank you

**Comment by pcislocked** [comment]
don't remember it, was a long time ago, probably did the form

**Comment by beckyandcloud** [comment]
I used this one year old video to help me going through the form, if it can help someone else :
https://www.youtube.com/watch?v=dhrv5RhKewA&t=54s

**Comment by grnqrtr** [comment]
I filled out this form and got a response in 4 days from YouTube and can now upload videos that are publicly viewable.
https://support.google.com/youtube/contact/yt_api_form

**Comment by colemar** [comment]
> Just wanted to write my experience with the youtube api team
> 
> I sent a quota request directly linking this repository and stating my use case(just personal use - specifically reuploading lecture recordings from sharepoint to youtube as unlisted) - got my quota increase within a week. I asked for and got 20k per day - which is more than enough for me. Quota got increased and the keys started working immediately after the response mail.

Does it make sense to start with much less "Queries per day" than "Queries per minute"?
Also, I see "Queries per day" being eroded, but not "Queries per minute" or  "Queries per minute per user".
![image](https://github.com/tokland/youtube-upload/assets/3066000/0b81fde9-0c21-4526-9ef0-64466bdf4da3)

**Comment by rsacherer** [comment]
Hi guys, 

I am a bit confused, what am I supposed to enter here:

    Application logo
    Authorized domains
    Application Homepage link
    Application Privacy Policy link
    Application Terms of Service link


I just want to use this script to upload my son's soccer games, I don't have a homepage or privacy policy or TOS ...

What did you guys enter there?

Thank you,

**Comment by colemar** [comment]
@muahdib69 
Application logo: I do not remember having put in something.
Authorized domains: same as above.
Application Homepage link: https://github.com/tokland/youtube-upload
Application Privacy Policy link: https://github.com/tokland/youtube-upload
Application Terms of Service link: https://github.com/tokland/youtube-upload

Unfortunately I cannot recover the submitted form, but I referred to this repository as much as possible and after 2-3 days they got back to me asking for the explicit URL of the channel where the videos would be uploaded. I provided it and they final response was "We will conduct our review based on the information you provided. We will notify you if we need additional information, or when we’ve completed our review".
10 days have passed since then.

**Comment by rsacherer** [comment]
Ah, thank you, I tried this before, but it required the github.com domain, I know just put github.com there and the form did accept it ... let's see how it goes.

**Comment by colemar** [comment]
@muahdib69 I updated my last comment.

**Comment by Kathy-rine** [comment]
@ScottishWildlifeGarden I am in a similar situation. All the videos I upload to Youtube through an app script tool get locked private.
This is even after I have done the API verification (they even increased my daily token quota).
Did the API just magically works for you after some time?
I'm at my wit end since there is no way to contact any kind of support from Youtube and I have done all the trouble shooting I can think  of.

**Comment by LaserMoai** [comment]
I think the developer should add a disclaimer to the readme about this issue. The setup takes a while and the tool ends up being effectively useless for many.

**Comment by jeremytrane** [comment]
Does anyone know how much time it takes for YouTube to allow you to upload videos publicly once the API has been verified?

I submitted the form and got the email below 
"
Hello,

Thanks for working with us on the YouTube API Services compliance review. We have completed your review and don’t require any further actions from you at this time.

We may reach out again to re-review your API Client for compliance with YouTube API Services Terms and Policies.

We appreciate your cooperation with us. Please continue to comply with the YouTube API Services Terms and Policies.

Thanks,

The YouTube API Services Team
"

However this was four days ago and whenever I upload it still uploads them as private and locked.

**Comment by feacluster** [comment]
> Does anyone know how much time it takes for YouTube to allow you to upload videos publicly once the API has been verified?
> 
> I submitted the form and got the email below " Hello,
> 
> Thanks for working with us on the YouTube API Services compliance review. We have completed your review and don’t require any further actions from you at this time.
> 
> We may reach out again to re-review your API Client for compliance with YouTube API Services Terms and Policies.
> 
> We appreciate your cooperation with us. Please continue to comply with the YouTube API Services Terms and Policies.
> 
> Thanks,
> 
> The YouTube API Services Team "
> 
> However this was four days ago and whenever I upload it still uploads them as private and locked.

Can't remember, but probably was no more than a day after I got the email from Youtube. But now I am using a new tool, youtubeuploader . Maybe try posting your issue there as it is more active than this obsolete tool.

**Comment by jeremytrane** [comment]
I'll give that a go thank you

**Comment by heaven-born** [comment]
Here is my experience: my application was audited in about four days after I submitted the request. Then I waited more than 4 days but it didn't fix the "private (locked)" issue on video uploads. So I filled out another form originally designed to increase the quota for those who already have their project audited, but instead of explaining why I needed this quota increase, I explained that my video upload is not working after 74 hours. Surprisingly they replied and asked me to upload the video again and tell them if the issue was still there. I was trying to upload a videos a few more days after they replied and eventually the issue disappeared. I'm not sure if that was because I requested them to fix the issue or because more than 74 hours of waiting is needed.

**Comment by jeremytrane** [comment]
The issue has seem to be fixed it took 5 days for it to sort itself out thank you for your responses!
